export const GATEWAY = 'https://gw.b2binpay.com/api';
export const SANDBOX = 'https://gw-test.b2binpay.com/api';
export const TEST_KEY = '';
export const TEST_SECRET = '';
export const CURRENCY_URL = {
  BTC: 'https://btc.b2binpay.com',
  LTC: 'https://ltc.b2binpay.com',
  ETH: 'https://eth.b2binpay.com',
  XMR: 'https://xmr.b2binpay.com',
  BCH: 'https://bch.b2binpay.com',
  DASH: 'https://dash.b2binpay.com',
  NEO: 'https://neo.b2binpay.com',
  ADA: 'https://ada.b2binpay.com',
  DOGE: 'https://doge.b2binpay.com',
  ZEC: 'https://zec.b2binpay.com',
  B2BX: 'https://eth.b2binpay.com',
  USDT: 'https://omni.b2binpay.com',
  USDT_Ethereum: 'https://eth.b2binpay.com',
  OMG: 'https://eth.b2binpay.com',
  PAX: 'https://eth.b2binpay.com',
  TUSD: 'https://eth.b2binpay.com',
  GUSD: 'https://eth.b2binpay.com',
  USDC: 'https://eth.b2binpay.com',
  BWK: 'https://bwk.b2binpay.com',
  TRX: 'https://tron.b2binpay.com',
  DAI: 'https://eth.b2binpay.com',
  XRP: 'https://xrp.b2binpay.com',
  XLM: 'https://xlm.b2binpay.com',
  EOS: 'https://eos.b2binpay.com',
  BNB: 'https://bnb.b2binpay.com',
  NEM: 'https://nem.b2binpay.com',
};
export const SANDBOX_URL = {
  BTC: 'https://cr-test.b2binpay.com',
  LTC: 'https://cr-test.b2binpay.com',
  ETH: 'https://cr-test.b2binpay.com',
  XMR: 'https://cr-test.b2binpay.com',
  BCH: 'https://cr-test.b2binpay.com',
  DASH: 'https://cr-test.b2binpay.com',
  NEO: 'https://cr-test.b2binpay.com',
  ADA: 'https://cr-test.b2binpay.com',
  DOGE: 'https://cr-test.b2binpay.com',
  ZEC: 'https://cr-test.b2binpay.com',
  B2BX: 'https://cr-test.b2binpay.com',
  USDT: 'https://cr-test.b2binpay.com',
  USDT_Ethereum: 'https://cr-test.b2binpay.com',
  OMG: 'https://cr-test.b2binpay.com',
  PAX: 'https://cr-test.b2binpay.com',
  TUSD: 'https://cr-test.b2binpay.com',
  GUSD: 'https://cr-test.b2binpay.com',
  USDC: 'https://cr-test.b2binpay.com',
  BWK: 'https://cr-test.b2binpay.com',
  TRX: 'https://cr-test.b2binpay.com',
  DAI: 'https://cr-test.b2binpay.com',
  XRP: 'https://cr-test.b2binpay.com',
  XLM: 'https://cr-test.b2binpay.com',
  EOS: 'https://cr-test.b2binpay.com',
  BNB: 'https://cr-test.b2binpay.com',
  NEM: 'https://cr-test.b2binpay.com',
};
